GeoMap/GeoApp/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [

    path('', views.main, name='main'),
    path('proto', views.home, name='proto'),
    path('map', views.map, name='map'),
    path('map_two', views.map_two, name='map_two'),
    path('map_uno', views.map_uno, name='map_uno'),

    path('map_ajax', views.map_ajax, name='map_ajax'), #ajax
    path('test_ajax/<tt>', views.test_ajax, name='test_ajax'), #ajax
    path('map_uno_ajax', views.map_uno_ajax, name='map_uno_ajax'), #ajax
    path('poezd_suggest', views.poezd_suggest, name='poezd_suggest'), #ajax
    path('new_tab/<month>/<poezd>', views.map_two, name='new_tab') #ajax
    # path('odata', views.oData, name='odata'),
    # path('no_data', views.oData, name='no_data'),

]

GeoMap/GeoMap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GeoApp.urls')),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")))
]

GeoMap/GeoApp/models.py
from django.db import models

# Create your models here.

GeoMap/GeoApp/forms.py
import datetime
from django import forms
from django.forms import SelectDateWidget


class GetPoezd(forms.Form):
    month = forms.CharField(label='Период', widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'month',
                                                                          'placeholder': 'YYYY-MM',
                                                                          'pattern': '[0-9]{4}-[0-9]{2}'}))
    poezd = forms.CharField(max_length=16, label='Поезд', widget=forms.TextInput(attrs={'class': 'form-control'}))
    st_text = forms.BooleanField(label='Тексты', label_suffix=" : ",
                                 required=False, disabled=False,
                                 widget=forms.widgets.CheckboxInput(attrs={'class': 'checkbox-inline'}),
                                 help_text="...",
                                 error_messages={'required': "Please check the box"})


class GetUno(forms.Form):
    month = forms.CharField(label='Период', widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'month',
                                                                          'placeholder': 'YYYY-MM',
                                                                          'pattern': '[0-9]{4}-[0-9]{2}'}))
    uno = forms.CharField(max_length=12, label='УНО', widget=forms.TextInput(attrs={'class': 'form-control'}))
    iddos = forms.CharField(max_length=10, label='ID досылки', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

GeoMap/GeoApp/views.py
from django.shortcuts import render, redirect
from . import map_editor, Server_connector
from .forms import GetPoezd, GetUno
from django.contrib import messages
from django.http import JsonResponse, HttpResponse


# Create your views here.


def main(request):
    return render(request, 'GeoApp/main.html', {})


def home(request):
    form = GetPoezd()
    return render(request, 'GeoApp/index.html', {'form': form})


def map(request):
    month_form = ''
    poezd_form = ''
    form = ''
    if request.method == 'POST':
        form = GetPoezd(request.POST)
        if form.is_valid():
            month_form = form.cleaned_data['month'].replace("-", "")
            poezd_form = form.cleaned_data['poezd']

    map, error, no_coord, numbering, start_end_meta = map_editor.getMap(month_form, poezd_form)

    context = {'my_map': map,
               'no_coord': no_coord}
    if error:
        messages.error(request, 'Нет данных')
        return render(request, 'GeoApp/index.html', {'form': form})
        # return render(request, 'GeoApp/no_data.html', context)
    else:
        return render(request, 'GeoApp/home.html', context)


def map_two(request, month='', poezd=''):
    if month:
        initial_dict = {
            "month": month,
            "poezd": poezd,
        }
        form = GetPoezd(initial=initial_dict)
        response = {'form': form,
                    'autosubmit': 'True'}
    else:
        form = GetPoezd()
        response = {'form': form}

    return render(request, 'GeoApp/map_two.html', response)


def map_uno(request):
    form = GetUno()
    return render(request, 'GeoApp/map_uno.html', {'form': form})


def map_uno_ajax(request):
    month = ''
    uno = ''
    iddos = ''
    form = GetUno(request.POST)
    if form.is_valid():
        month = form.cleaned_data['month'].replace("-", "")
        uno = form.cleaned_data['uno']
        uno = str(uno).zfill(12)
        iddos = form.cleaned_data['iddos']
        iddos = str(iddos).zfill(10)

    # ajax_map, error, no_coord, start_end_meta, numbering, uno_list = map_editor.getMapUno(month, uno, iddos)
    # uno_map, uno_no_coord = map_editor.getMapUnoCut(month, uno, iddos)

    ajax_map, error, no_coord, start_end_meta, numbering, uno_list, uno_map, uno_no_coord = map_editor.getMapUnoSOAP(month, uno, iddos)

    response = {'ajax_map': ajax_map,
                'no_coord': no_coord,
                'start_end_meta': start_end_meta,
                'numbering': numbering,
                'uno_list': uno_list,
                'uno_map': uno_map,
                'uno_no_coord': uno_no_coord}
    return JsonResponse(response)


def map_ajax(request):
    poezd = ''
    month = ''
    form = GetPoezd(request.POST)
    st_text = False
    if form.is_valid():
        month = form.cleaned_data['month'].replace("-", "")
        poezd = form.cleaned_data['poezd']
        poezd = str(poezd).zfill(16)
        st_text = form.cleaned_data['st_text']

    # ajax_map, error, no_coord, numbering, start_end_meta = map_editor.getMap(month, poezd, icon_text=st_text)
    ajax_map, error, no_coord, numbering, start_end_meta = map_editor.getMapSOAP(month, poezd, icon_text=st_text)
    response = {'ajax_map': ajax_map,
                'no_coord': no_coord,
                'numbering': numbering,
                'start_end_meta': start_end_meta}

    return JsonResponse(response)


def test_ajax(request, tt):
    table = [{'col1': '123', 'col2': '321', 'col3': 'abc', 'col4': 'cab'}]
    response = {'data1': table}
    print(tt)

    return JsonResponse(response)


def poezd_suggest(request):
    pattern = request.GET.get('search_keyword')
    pattern = '%' + pattern + '%'
    filter = '?poezd=' + pattern
    # poezd_json = Server_connector.get_set('PoezdSuggest', filter)
    # response = {'trains_code': poezd_json}
    # return JsonResponse(response)
    return JsonResponse({})


def new_tab(request):
    pattern = request.GET.get('data')
    print(pattern)
    return redirect('map_two.html', {'form': 'form'})

GeoMap/GeoApp/templates/GeoApp/home.html
{% extends 'GeoApp/base.html' %}

{% block title %}
Карта
{% endblock %}


<!-- Page Content -->

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-12 text-center">

            <div class="pad_5"></div>

            {{ my_map|safe }}

        </div>

    </div>

    <div class="row">
        <table  class="table">
        {% if no_coord %}
        <th>Нет координат для</th>
            <th>/BIC/AZGO_GEO2</th>
        {% endif %}
        {% for line in no_coord %}
        <tr>
           <td>{{ line.STANTION }}</td>
        </tr>
        {% endfor %}
        </table>
    </div>

</div>



{% endblock %}

GeoMap/GeoApp/templates/GeoApp/index.html
{% extends 'GeoApp/base.html' %}

{% block title %}
Ввод параметров
{% endblock %}

{% block content %}
<section class="h-100 h-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <div class="card rounded-3">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img3.webp"
                         class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                         alt="Sample photo">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Параметры</h3>

                        <!--соурс формы https://mdbootstrap.com/docs/standard/extended/registration/-->

                        {% for message in messages %}
                        <div class=" mb-2   alert alert-danger">
                            {{ message }}
                        </div>
                        {% endfor %}

                        <form class="px-md-2" action="{% url 'map' %}" method="POST">
                            {% csrf_token %}
                            <div class=" form-outline mb-4">
                                <lable class="form-label" for="{{ form.month.id_for_label }}">{{ form.month.label }}:
                                </lable>
                                {{ form.month }}
                            </div>
                            <div class="form-outline mb-4">
                                <lable class="form-label" for="{{ form.poezd.id_for_label }}">{{ form.poezd.label }}:
                                </lable>
                                {{ form.poezd }}
                            </div>
                            <button type="submit" class="btn btn-success btn-lg mb-1">Отобразить маршрут</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>


</script>

{% endblock %}

GeoMap/GeoApp/templates/GeoApp/map_two.html
{% extends 'GeoApp/base.html' %}

{% block title %}
Проследование
{% endblock %}

{% block style %}

<style type="text/css">
    .fix_r {
        top: 15%;
        right: 0;
        position: fixed;
        overflow-y: auto;
        max-height: 70%;
    }
    .table {
        table-layout: fixed;
        border-collapse: collapse;
    }
    .table tbody {
      display: block;
      width: 100%;
      overflow: auto;
      height: 100%;
    }
    .table thead tr {
      display: block;
    }
    #numHeader{
        overflow-y: auto;
        max-height: 530px;
    }

    /*switch*/
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked + .slider {
        background-color: #2196F3;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }
/*switch*/

</style>

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <main class="col-md-9  col-lg-8 px-md-4">
            <div
                    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <section class="h-100 h-custom w-100">

                    <form id="my_form" class="px-md-2" method="POST">
                        {% csrf_token %}
                        <div class=" form-outline mb-4">
                            <lable class="form-label" for="{{ form.month.id_for_label }}">{{ form.month.label }}:
                            </lable>
                            {{ form.month }}
                        </div>
                        <div class="form-outline mb-4">
                            <lable class="form-label" for="{{ form.poezd.id_for_label }}">{{ form.poezd.label }}:
                            </lable>
                            {{ form.poezd }}
                        </div>
                        <div class="form-outline mb-4">
                            <lable class="form-label" for="{{ form.poezd.id_for_label }}">Режим скриншота:
                            </lable> <br>
                            <label class="switch">
                                {{ form.st_text }}
                                <span class="slider"></span>
                            </label>
                        </div>
                        <button id="subb" type="submit" class="btn btn-success btn-lg mb-1">Отобразить маршрут</button>
                    </form>
                </section>

            </div>

            <h2>Проследование</h2>
            <div class="container">

                <div class="row">

                    <div class="col-lg-12 text-center">

                        <div class="pad_5"></div>

                        <div id="mapper" style="width: 100%"></div>

                    </div>

                </div>

                <div class="row">
                    <table id="my_table" class="table">
                    </table>
                </div>

            </div>
        </main>
        <nav id="sidebarMenu" class="col-md-2 col-lg-4 d-md-block sidebar collapse fix_r">
            <div id="start_end"></div>
            <table class="table">
                <tr>
                    <th>Станция начала</th>
                    <th>Станция конца</th>
                    <th>&#8470;</th>
                    <th>Код участка</th>
                    <th>Четность</th>
                </tr>
                <tbody id="numHeader">

                </tbody>

            </table>
        </nav>
    </div>
</div>

<!--<section class="h-100 h-custom">
    <div class="container py-5 h-100">
        <form id="my_form" class="px-md-2" method="POST">
            {% csrf_token %}
            <div class=" form-outline mb-4">
                <lable class="form-label" for="{{ form.month.id_for_label }}">{{ form.month.label }}:
                </lable>
                {{ form.month }}
            </div>
            <div class="form-outline mb-4">
                <lable class="form-label" for="{{ form.poezd.id_for_label }}">{{ form.poezd.label }}:
                </lable>
                {{ form.poezd }}
            </div>
            <button id="subb" type="submit" class="btn btn-success btn-lg mb-1">Отобразить маршрут</button>
        </form>

    </div>
</section>

<div class="fix_r">
    <table id="my_table1" class="table">
        <tr>
            <th>Станция начала</th>
            <th>Станция конца</th>
            <th>Номер</th>
            <th>Код участка</th>
            <th>Четность</th>
        </tr>
        <tr>
            <td>qqqqqq</td>
            <td>qqqqqq</td>
            <td>qqqqqq</td>
        </tr>
    </table>
</div>-->

<!--<div class="container">

    <div class="row">

        <div class="col-lg-12 text-center">

            <div class="pad_5"></div>

            <div id="mapper" style="width: 100%"></div>

        </div>

    </div>

    <div class="row">
        <table id="my_table" class="table">
        </table>
    </div>

    </div>-->

<script>

    /*   $('#my_form').submit(function() {
       $.ajax({ data: $(this).serialize(), // получаяем данные
                      url: "{% url 'map_ajax' %}",
                      type:"post",
                      // если успешно, то
                      success: function (response) {
                        var block = document.getElementById("mapper");
                        block = response.ajax_map
                      },
                      // если ошибка, то
                      error: function (response) {
                          // предупредим об ошибке
                          console.log(response.responseJSON.errors)
                      }
                 });
   
       });*/
    
    $(function () {
        $("#my_form").submit(function (event) {
            // Stop form from submitting normally
            event.preventDefault();
            var friendForm = $(this);
            // Send the data using post
            var posting = $.post("{% url 'map_ajax' %}", friendForm.serialize());
            // if success:
            posting.done(function (data) {
                document.getElementById("mapper").innerHTML = "";
                var block = document.getElementById("mapper");
                block.insertAdjacentHTML('afterbegin', data.ajax_map)

                document.getElementById("my_table").innerHTML = "";
                if (data.no_coord) {
                    document.getElementById("my_table").insertAdjacentHTML('afterbegin', '<th>Нет координат для</th> <th>/BIC/AZGO_GEO2</th>');
                }
                for (i in data.no_coord) {
                    document.getElementById("my_table").insertAdjacentHTML('beforeend', '<tr><td>' + data.no_coord[i].STANTION + '</td></tr>');
                };

                document.getElementById("numHeader").innerHTML = "";
                for (i in data.numbering) {
                    //document.getElementById("numHeader").insertAdjacentHTML('beforeend', '<tr>');
                    document.getElementById("numHeader").insertAdjacentHTML('beforeend', '<td>' + data.numbering[i].STANTION_START + '</td>' +
                        '<td>' + data.numbering[i].STANTION_FINISH + '</td>' +
                        '<td>' + data.numbering[i].NUMBER + '</td>' +
                        '<td>' + data.numbering[i].CASAR + '</td>' +
                        '<td>' + data.numbering[i].CHET + '</td>');


                    /*document.getElementById("numHeader").insertAdjacentHTML('beforeend', '<td>' + data.numbering[i].STANTION_FINISH + '</td>');
                    document.getElementById("numHeader").insertAdjacentHTML('beforeend', '<td>' + data.numbering[i].NUMBER + '</td>');
                    document.getElementById("numHeader").insertAdjacentHTML('beforeend', '<td>' + data.numbering[i].CASAR + '</td>');
                    document.getElementById("numHeader").insertAdjacentHTML('beforeend', '<td>' + data.numbering[i].CHET + '</td>');*/
                    //document.getElementById("numHeader").insertAdjacentHTML('beforeend', '</tr>');
                }

                document.getElementById("start_end").innerHTML = "";
                document.getElementById("start_end").insertAdjacentHTML('beforeend', '<h3> Станция начала: ' + data.start_end_meta[0].stantion_start
                                                                        + '-' + data.start_end_meta[0].stantion_start_name + '</h3>');
                document.getElementById("start_end").insertAdjacentHTML('beforeend', '<h3> Станция конца: ' + data.start_end_meta[0].stantion_finish
                                                                        + '-' + data.start_end_meta[0].stantion_finish_name + '</h3>');


            });
            // if failure:
            posting.fail(function (data) {
                // 4xx or 5xx response, alert user about failure
                console.log(data.responseJSON.errors)
            });
        });
    });

    /*$(function () {
        function myFunction() {
            /*var availableTags = [
                {% for language in languages %}
                    "{{ language.name }}",
                {% endfor %}
            ];
            $( "#tags" ).autocomplete({
              source: availableTags
            });
            alert('aaa');
        }
    });*/

    $(function () {
        var minlength = 3;

        $("#id_poezd").keyup(function () {
            value = $(this).val();

            if (value.length >= minlength) {
                searchRequest = $.ajax({
                    type: "GET",
                    url: "{% url 'poezd_suggest' %}",
                    data: {
                        'search_keyword': value
                    },
                    //dataType: "text",
                    success: function (data) {
                        $("#id_poezd").autocomplete({
                            source: data.trains_code
                        });


                    }
                });
            }
        });
    });

    $(function(){
        let autosubmit = "{{autosubmit}}";
        if( autosubmit === 'True' ){

            document.getElementById("subb").click();
        }
        
    })


</script>

{% endblock %}

GeoMap/GeoApp/templates/GeoApp/map_uno.html
{% extends 'GeoApp/base.html' %}

{% block title %}
Проследование
{% endblock %}

{% block style %}

<style type="text/css">
    .fix_r {
        top: 15%;
        right: 0;
        position: fixed;
        overflow-y: auto;
        /*max-height: 70%;*/
    }
    .table {
        table-layout: fixed;
        border-collapse: collapse;
    }
    .table tbody {
      display: block;
      width: 100%;
      overflow: auto;
      height: 100%;
    }
    .table thead tr {
      display: block;
    }
    #numHeader, #unoList{
        overflow-y: auto;
        max-height: 530px;
    }

    /*switch*/
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #2196F3;/*#ccc;*/
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked + .slider {
        background-color: #2196F3;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    #uno_list, #mapper_uno, #uno_no_cord{
        display: none;
    }

    #sw_uno_train{
        font-size: 20px;
        text-align: center;
        letter-spacing: 5px;
    }
/*switch*/

</style>

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <main class="col-md-9  col-lg-8 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <section class="h-100 h-custom w-100">

                    <form id="my_form" class="px-md-2" method="POST">
                        {% csrf_token %}
                        <div class=" form-outline mb-4">
                            <lable class="form-label" for="{{ form.month.id_for_label }}">{{ form.month.label }}:
                            </lable>
                            {{ form.month }}
                        </div>
                        <div class="form-outline mb-4">
                            <lable class="form-label" for="{{ form.poezd.id_for_label }}">{{ form.uno.label }}:
                            </lable>
                            {{ form.uno }}
                        </div>
                        <div class="form-outline mb-4">
                            <lable class="form-label" for="{{ form.poezd.id_for_label }}">{{ form.iddos.label }}:
                            </lable>
                            {{ form.iddos }}
                        </div>
                        <button id="subb" type="submit" class="btn btn-success btn-lg mb-1">Отобразить маршрут</button>
                    </form>
                </section>

            </div>

            <h2>Проследование</h2>
            <div class="container">

                <div class="row">

                    <div class="col-lg-12 text-center">

                        <div class="pad_5"></div>

                        <div id="mapper" style="width: 100%"></div>
                        <div id="mapper_uno" style="width: 100%"></div>

                    </div>

                </div>

                <div class="row">
                    <table id="my_table" class="table">
                    </table>
                    <table id="uno_no_cord" class="table">
                    </table>
                </div>

            </div>
        </main>
        <nav id="sidebarMenu" class="col-md-2 col-lg-4 d-md-block sidebar collapse fix_r">
            <div id="sw_uno_train"> По станциям
            <label class="switch">
                <input type="checkbox" id="train_uno_box" onchange="listChangeViz()">
                 <span class="slider"></span>
            </label> По поездам </div><br>
            <div id="start_end"></div>
            <table class="table" id="train_list">
                <thead>
                <tr>
                    <th>Станция начала</th>
                    <th>Станция конца</th>
                    <th>&#8470;</th>
                    <th>Код участка</th>
                    <th>Четность</th>
                </tr>
                </thead>
                <tbody id="numHeader">

                </tbody>
            </table>

            <table class="table" id="uno_list">
            <!--<table class="display" style="width:100%" id="uno_list">-->
                <thead>
                <tr>
                    <th>№</th>
                    <th>Поезд</th>
                    <th>Станция отправления</th>
                    <th>Название</th>
                    <th>Станция назначения</th>
                    <th>Название</th>
                </tr>
                </thead>
                <tbody id="unoList">

                </tbody>
            </table>

        </nav>
    </div>
</div>

<script>

    $(function () {
        $("#my_form").submit(function (event) {
            // Stop form from submitting normally
            event.preventDefault();
            var friendForm = $(this);
            // Send the data using post
            var posting = $.post("{% url 'map_uno_ajax' %}", friendForm.serialize());

            document.getElementById("mapper").innerHTML = "<h2>Идет построение карты...<h2>";
            document.getElementById("my_table").innerHTML = "";

            document.getElementById("mapper_uno").innerHTML = "<h2>Идет построение карты...<h2>";
            document.getElementById("uno_no_cord").innerHTML = "";

            // if success:
            posting.done(function (data) {
                document.getElementById("mapper").innerHTML = "";
                var block = document.getElementById("mapper");
                block.insertAdjacentHTML('afterbegin', data.ajax_map)

                document.getElementById("mapper_uno").innerHTML = "";
                var block = document.getElementById("mapper_uno");
                block.insertAdjacentHTML('afterbegin', data.uno_map)

                document.getElementById("my_table").innerHTML = "";
                if (data.no_coord) {
                    document.getElementById("my_table").insertAdjacentHTML('afterbegin', '<th>Нет координат для</th> <th>/BIC/AZGO_GEO2</th>');
                }
                for (i in data.no_coord) {
                    document.getElementById("my_table").insertAdjacentHTML('beforeend', '<tr><td>' + data.no_coord[i].STANTION + '</td></tr>');
                };

                for (i in data.uno_no_coord) {
                    document.getElementById("uno_no_cord").insertAdjacentHTML('beforeend', '<tr><td>' + data.no_coord[i].STANTION + '</td></tr>');
                };

                document.getElementById("numHeader").innerHTML = "";
                for (i in data.numbering) {
                    //document.getElementById("numHeader").insertAdjacentHTML('beforeend', '<tr>');
                    document.getElementById("numHeader").insertAdjacentHTML('beforeend', '<td>' + data.numbering[i].STANTION_START + '</td>' +
                        '<td>' + data.numbering[i].STANTION_FINISH + '</td>' +
                        '<td>' + data.numbering[i].NUMBER + '</td>' +
                        '<td>' + data.numbering[i].CASAR + '</td>' +
                        '<td>' + data.numbering[i].CHET + '</td>');

                }

                document.getElementById("start_end").innerHTML = "";
                document.getElementById("start_end").insertAdjacentHTML('beforeend', '<h3> Станция начала: ' + data.start_end_meta[0].stantion_start
                                                                        + '-' + data.start_end_meta[0].stantion_start_name + '</h3>');
                document.getElementById("start_end").insertAdjacentHTML('beforeend', '<h3> Станция конца: ' + data.start_end_meta[0].stantion_finish
                                                                        + '-' + data.start_end_meta[0].stantion_finish_name + '</h3>');

                
                document.getElementById("unoList").innerHTML = "";
                for (i in data.uno_list) {
                    let month_val = document.getElementById('id_month').value;
                    let poezd_val = data.uno_list[i].POEZD
                    //let url = "{% url 'new_tab' month="+ month_val +" poezd="+poezd_val+" %}";
                    let url = 'new_tab/'+ month_val + '/' + poezd_val;

                    document.getElementById("unoList").insertAdjacentHTML('beforeend', 
                        '<td>' + data.uno_list[i].SERIAL_NUMBER + '</td>' +
                        '<td><a href="'+ url + '"target="_blank" class="link-secondary">' + data.uno_list[i].POEZD + '</a></td>' +
                        '<td>' + data.uno_list[i].ST_START_CODE + '</td>' +
                        '<td>' + data.uno_list[i].STANTION_START + '</td>' +
                        '<td>' + data.uno_list[i].ST_FINISH_CODE + '</td>' +
                        '<td>' + data.uno_list[i].STANTION_FINISH + '</td>');
                } 
                //$('#uno_list').DataTable();
            });
            // if failure:
            posting.fail(function (data) {
                // 4xx or 5xx response, alert user about failure
                console.log(data.responseJSON.errors)
            });
        });
    });

    $(function () {
        var minlength = 3;

        $("#id_poezd").keyup(function () {
            value = $(this).val();

            if (value.length >= minlength) {
                searchRequest = $.ajax({
                    type: "GET",
                    url: "{% url 'poezd_suggest' %}",
                    data: {
                        'search_keyword': value
                    },
                    //dataType: "text",
                    success: function (data) {
                        $("#id_poezd").autocomplete({
                            source: data.trains_code
                        });
                    }
                });
            }
        });
    });

function listChangeViz(){
    const box = document.querySelector('#train_uno_box'); 
    if (box.checked){
        $("#train_list").hide();
        $("#uno_list").show();
        
        $("#uno_no_cord").show();
        $("#my_table").hide();
        
        $("#mapper_uno").show();        
        $("#mapper").hide();
    } else {
        $("#train_list").show();
        $("#uno_list").hide();

        $("#uno_no_cord").hide();
        $("#my_table").show();
        
        $("#mapper_uno").hide();        
        $("#mapper").show();
    }
}

</script>

{% endblock %}